### PR TITLE
Upgrade to v5.30.x

### PR DESCRIPTION
**Pull request by jleni**

### CODE REVIEW

**Comment by tededi** [comment]
Do we know when the new Kusama ledger update will be finished? thanks

**Comment by tededi** [comment]
Its not working on Ledger. Please sort the issue or give us a heads up on the timeframe ?

**Comment by peter1401maier** [comment]
> Thank you for your hard work

Is it possible to make a transaction with the ledger nano again? It does not work for me.

**Comment by tededi** [comment]
When will this be on Ledger Live please? can anyone help?

**Pull request merged**
